name: Docker image build and push
on: [push] #push触发
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code #检查仓库代码
        uses: actions/checkout@v5
      - name: docker image build #创建镜像
        run: docker image build -t 873933753/docker-practice:latest .
      - name: list docker image # 镜像列表
        run: docker image ls
      - name: dockerhub login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: push to dockerhub
        run:docker image push 873933753/docker-practice:latest
